---
title: "qCLASH exploration"
author: "Hailee Herbst"
date: "8/8/2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(ggrepel)
library(ggplot2)
library(ggpubr)
```

```{r}
hyb_sensitive <- readRDS(here::here("initial_data/hyb_sensitive.rds"))
hyb_resistant <- readRDS(here::here("initial_data/hyb_resistant.rds"))
miRNA_DE <- readRDS(here::here("initial_data/DEGS_smallRNAseq.rds"))
hyb_network <- readRDS(here::here("initial_data/resistant_hybrids_qCLASH_network.RDS"))
```


#Number of hybrids identified in each cell line
```{r}
hyb_resistant %>% 
  filter(Binding_Region!="unknown") %>%
  transform(cell_line=factor(cell_line, levels = c("IPC_R", "SK30_R"))) %>%
  ggplot(aes(x=Sample))+
  geom_bar(aes(fill=cell_line))+
  geom_text(stat='count', aes(label=..count..), vjust=2)+
  xlab("")+
  ylab("Number of Hybrids")+
  theme_bw(10)+
  facet_wrap(~cell_line, ncol=3, scales="free_x")+
  ggtitle("Total Number of Hybrids")+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_fill_manual("cell_line", values = c("IPC_R" = "darkolivegreen4",
                                            "SK30_R"="steelblue3"))


hyb_network %>% 
  filter(Binding_Region!="unknown") %>%
  transform(cell_line=factor(cell_line, levels = c("IPC_R", "SK30_R"))) %>%
  ggplot(aes(x=Sample))+
  geom_bar(aes(fill=cell_line))+
  geom_text(stat='count', aes(label=..count..), vjust=2)+
  xlab("")+
  ylab("Number of Hybrids")+
  theme_bw(10)+
  facet_wrap(~cell_line, ncol=3, scales="free_x")+
  ggtitle("Total Number of Hybrids")+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_fill_manual("cell_line", values = c("IPC_R" = "darkolivegreen4",
                                            "SK30_R"="steelblue3"))
```



# Binding regions of hybrids, by cell line and replicate
```{r}
hyb_resistant  %>%
  transform(cell_line=factor(cell_line, levels = c("IPC_R", "SK30_R"))) %>%
  # filter(Binding_Region!="test") %>% 
  ggplot(aes(x=Sample, y=..count..))+
  geom_bar(aes(fill=Binding_Region), position="fill", colour="black")+
  theme_bw(12)+
  theme(text=element_text(size=20)) +
  theme(legend.text=element_text(size=26)) +
  xlab("")+
  ylab("Proportion of miRNA-mRNA hybrids")+
  ggtitle("Binding Regions of All qCLASH Hybrids")+
  theme(plot.title = element_text(hjust = 0.5))+
  facet_wrap(~cell_line, ncol=3, scales="free")+
  scale_fill_manual("Binding Region", values = c("3'UTR" = "seagreen3", 
                                                 "5'UTR" = "burlywood1",
                                                 "CDS" = "palevioletred",
                                                 "5'UTR-CDS" = "steelblue2",
                                                 "CDS-3'UTR" = "cornsilk",
                                                 "unknown"="slategrey"))


hyb_network  %>%
  transform(cell_line=factor(cell_line, levels = c("IPC_R", "SK30_R"))) %>%
  # filter(Binding_Region!="test") %>% 
  ggplot(aes(x=Sample, y=..count..))+
  geom_bar(aes(fill=Binding_Region), position="fill", colour="black")+
  theme_bw(12)+
  theme(text=element_text(size=20)) +
  theme(legend.text=element_text(size=26)) +
  xlab("")+
  ylab("Proportion of miRNA-mRNA hybrids")+
  ggtitle("Binding Regions of Reduced Network Hybrids")+
  theme(plot.title = element_text(hjust = 0.5))+
  facet_wrap(~cell_line, ncol=3, scales="free")+
  scale_fill_manual("Binding Region", values = c("3'UTR" = "seagreen3", 
                                                 "5'UTR" = "burlywood1",
                                                 "CDS" = "palevioletred",
                                                 "5'UTR-CDS" = "steelblue2",
                                                 "CDS-3'UTR" = "cornsilk",
                                                 "unknown"="slategrey"))


```



# Seed region of miRNA, by cell line and replicate
```{r}

hyb_resistant  %>%
  transform(cell_line=factor(cell_line, levels = c("IPC_R", "SK30_R"))) %>%
  # filter(Binding_Region!="test") %>% 
  ggplot(aes(x=Sample, y=..count..))+
  geom_bar(aes(fill=Seed), position="fill", colour="black")+
  theme_bw(12)+
  theme(text=element_text(size=20)) +
  xlab("")+
  ylab("Proportion of miRNA-mRNA hybrids")+
  ggtitle("Seed Region of All qCLASH Hybrids")+
  theme(plot.title = element_text(hjust = 0.5))+
  facet_wrap(~cell_line, ncol=3, scales="free")+
  scale_fill_manual("Seed Region", values = c("other" = "darkgreen", 
                                              "2-8 no mismatches" = "steelblue",
                                              "2-7 no mismatches" = "plum4",
                                              "2-8 one mismatch" = "cornsilk",
                                              "2-7 one mismatch"="darkseagreen1",
                                              "2-8 two mismatches" = "lightcoral",
                                              "2-8 two mismatches" = "burlywood1"))


hyb_network  %>%
  transform(cell_line=factor(cell_line, levels = c("IPC_R", "SK30_R"))) %>%
  # filter(Binding_Region!="test") %>% 
  ggplot(aes(x=Sample, y=..count..))+
  geom_bar(aes(fill=Seed), position="fill", colour="black")+
  theme_bw(12)+
  theme(text=element_text(size=20)) +
  theme(legend.text=element_text(size=26)) +
  xlab("")+
  ylab("Proportion of miRNA-mRNA hybrids")+
  ggtitle("Seed Region of Reduced Network Hybrids")+
  facet_wrap(~cell_line, ncol=3, scales="free")+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_fill_manual("Seed", values = c("other" = "darkgreen", 
                                              "2-8 no mismatches" = "steelblue",
                                              "2-7 no mismatches" = "plum4",
                                              "2-8 one mismatch" = "cornsilk",
                                              "2-7 one mismatch"="darkseagreen1",
                                              "2-8 two mismatches" = "lightcoral",
                                              "2-8 two mismatches" = "burlywood1"))

```













