---
title: "PCA of Stringent Threshold Network"
author: "Hailee Herbst"
date: "08/04/2022"
output:
  html_notebook:
    code_folding: hide
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggpubr)
library(UpSetR)
library(ggupset)
library(dplyr)

```

# Gather total data

```{r}
qCLASH_untreated <- readRDS(here::here("data/hyb_sensitive.rds"))
qCLASH_treated <- readRDS(here::here("data/hyb_resistant.rds"))
threshold_hybrids <- readRDS(here::here("data/stringent_threshold.rds"))

```

# Parse out dataframes 

```{r}
# first qCLASH data

IPC_hyb <- qCLASH_untreated %>% filter(grepl("IPC298", cell_line))
SKMel_hyb <- qCLASH_untreated %>% filter(grepl("SKMel30", cell_line))

IPC_R_hyb <- qCLASH_treated %>% filter(grepl("IPC_R", cell_line))
SKMel_R_hyb <- qCLASH_treated %>% filter(grepl("SK30_R", Sample))

# second threshold data

IPC_thresh_hyb <- threshold_hybrids %>% filter(grepl("^IPC$", cell_line))
SKMel_thresh_hyb <- threshold_hybrids %>% filter(grepl("^SK$", cell_line))
IPC_R_thresh_hyb <- threshold_hybrids %>% filter(grepl("IPC_R", cell_line))
SKMel_R_thresh_hyb <- threshold_hybrids %>% filter(grepl("SK_R", cell_line))
```


# Join individual cell line and treatment types
```{r}
SK_R <- semi_join(SKMel_R_hyb, SKMel_R_thresh_hyb, by = "hybrids")
SK <- semi_join(SKMel_hyb, SKMel_thresh_hyb, by = "hybrids")
IPC_R <- semi_join(IPC_R_hyb, IPC_R_thresh_hyb, by = "hybrids")
IPC <- semi_join(IPC_hyb, IPC_thresh_hyb, by = "hybrids")
```


# Create one dataframe of all 
```{r}
threshold_qCLASH <- bind_rows(SK_R, SK, IPC_R, IPC)
saveRDS(threshold_qCLASH, "threshold_qCLASH.RDS")
```




# Create a count table of hybrids
```{r}
hybrid_count_table <- readRDS(here::here("data/hybrid_as_count_table.rds"))

unique_hybrids <- as.data.frame(unique(threshold_hybrids$hybrids, incomparables = FALSE))
names(unique_hybrids)[names(unique_hybrids) == 'unique(threshold_hybrids$hybrids, incomparables = FALSE)'] <- 'hybrids'
IPC_R_count <- hybrid_count_table[1:4]
IPC_R_count <- semi_join(IPC_R_count, IPC_R_thresh_hyb, by = "hybrids")
SK_R_count <- hybrid_count_table[, c(1,5:7)]
SK_R_count <- semi_join(SK_R_count, SKMel_R_thresh_hyb, by = "hybrids")
IPC_count <- hybrid_count_table[,c(1, 8:10)]
IPC_count <- semi_join(IPC_count, IPC_thresh_hyb, by = "hybrids")
SK_count <- hybrid_count_table[,c(1, 11:13)]
SK_count <- semi_join(SK_count, SKMel_thresh_hyb, by = "hybrids")

count_table_threshold <- left_join(unique_hybrids, IPC_R_count, by = "hybrids")
count_table_threshold <- left_join(count_table_threshold, SK_R_count, by = "hybrids")
count_table_threshold <- left_join(count_table_threshold, IPC_count, by = "hybrids")
count_table_threshold <- left_join(count_table_threshold, SK_count, by = "hybrids")

saveRDS(count_table_threshold, "count_table_threshold.RDS")
```



